// <auto-generated />
namespace Gevi.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SecambiaclaseUsuarioparaEmailunicoyformatodefecha : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecambiaclaseUsuarioparaEmailunicoyformatodefecha));
        
        string IMigrationMetadata.Id
        {
            get { return "201912152230360_Se cambia clase Usuario para Email unico y formato de fecha"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
