// <auto-generated />
namespace Gevi.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class seagregafechainicioaproyectosequitapaisacliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seagregafechainicioaproyectosequitapaisacliente));
        
        string IMigrationMetadata.Id
        {
            get { return "202002022206518_se agrega fechainicio a proyecto. se quita pais a cliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
