// <auto-generated />
namespace Gevi.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class seagregaelclienteengasto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seagregaelclienteengasto));
        
        string IMigrationMetadata.Id
        {
            get { return "202001270025510_se agrega el cliente en gasto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
